name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
    test:
      name: Run Tests
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout Code
          uses: actions/checkout@v3
  
        - name: Set up Python
          uses: actions/setup-python@v3
          with:
            python-version: '3.10'
  
        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
  
        - name: Set Environment Variables
          run: |
            echo "WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }}" >> $GITHUB_ENV
            echo "MAPQUEST_API_KEY=${{ secrets.MAPQUEST_API_KEY }}" >> $GITHUB_ENV
  
        - name: Run Tests
          run: pytest test_app.py
  
    deploy:
      name: Deploy Application
      runs-on: ubuntu-latest
      needs: test  # Runs only if "test" job is successful
  
      steps:
        - name: Checkout Code
          uses: actions/checkout@v3
  
        - name: Set Environment Variables
          run: |
            echo "WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }}" >> $GITHUB_ENV
            echo "MAPQUEST_API_KEY=${{ secrets.MAPQUEST_API_KEY }}" >> $GITHUB_ENV
